//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLancers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitor
    {
        public int ProjectID { get; set; }
        public int UserID { get; set; }
        public decimal Cost { get; set; }
        public int Duration { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
