//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLancers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCategory
    {
        public MainCategory()
        {
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int MainCategoryID { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
