
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FreeLancers.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Profile
{

    public Profile()
    {

        this.Comments = new HashSet<Comment>();

        this.Images = new HashSet<Image>();

        this.Skills = new HashSet<Skill>();

    }


    public int ProfileID { get; set; }

    public int UserID { get; set; }

    public string Description { get; set; }

    public int Experience { get; set; }

    public string LinkedURL { get; set; }

    public string YouTubeURL { get; set; }

    public string PreviousWork { get; set; }

    public Nullable<int> Rating { get; set; }

    public Nullable<bool> Featured { get; set; }

    public string CompanyName { get; set; }

    public int SubCategoryID { get; set; }

    public Nullable<System.DateTime> ExpiryDate { get; set; }

    public Nullable<int> ViewersCount { get; set; }



    public virtual ICollection<Comment> Comments { get; set; }

    public virtual ICollection<Image> Images { get; set; }

    public virtual SubCategory SubCategory { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<Skill> Skills { get; set; }

}

}
