
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FreeLancers.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.Comments = new HashSet<Comment>();

        this.Competitors = new HashSet<Competitor>();

        this.Profiles = new HashSet<Profile>();

        this.Projects = new HashSet<Project>();

        this.Requests = new HashSet<Request>();

        this.SubCategories = new HashSet<SubCategory>();

        this.ProjectsNotifications = new HashSet<Project>();

    }


    public int UserID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public Nullable<int> Mobile { get; set; }

    public int RoleID { get; set; }



    public virtual ICollection<Comment> Comments { get; set; }

    public virtual ICollection<Competitor> Competitors { get; set; }

    public virtual ICollection<Profile> Profiles { get; set; }

    public virtual ICollection<Project> Projects { get; set; }

    public virtual ICollection<Request> Requests { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<SubCategory> SubCategories { get; set; }

    public virtual ICollection<Project> ProjectsNotifications { get; set; }

}

}
